'''Statements: A statement is a unit of code that the Python interpreter can execute. It can be a simple statement or a compound statement.
 Simple Statement: A single line of code that performs a task.'''
 

# x = "HELLO WORLD"
# print(x)


'''
Indentation: Python uses indentation to define block structure instead of curly braces or keywords like begin and end as in other languages. Consistent indentation is crucial for Python's readability and correct interpretation of code.
'''

# if 3>2:
#     print("3 is greater tahan 2")
# else:
#     print(" noting ")
    
'''   
Variables: Variables are used to store data values. Python variables do not require explicit declaration; their data type is inferred from the value assigned to them.
'''

# x = 10
# name = "Alice"

'''
Comments: Comments are used to explain code and improve its readability. In Python, comments begin with the # symbol and continue to the end of the line.
'''
# This is a comment

'''
Conditional Statements (if, elif, else):
'''

# if mark>50:
#     print ("pass")      # what is the erorr in this code 
# elif mark<50:
#     print ("fail")
# else:
#    print ("noting")
   
   
'''Loops (for loop, while loop):'''


# for item student in tech_tonic:
#     print(student)
    
    
# for i in range (10):
#     print(i)
    

#     # Statements  
# while condition:
#     # Statements
    
    
'''Loop Control Statements (break, continue):'''

# for i in range (10):
#     if i==5:
#          continue
#     if i>7:
#          break 
    
'''Functions: Functions are blocks of reusable code that perform a specific task. They help in organizing code and promoting code reusability.
'''
# def greet(name):
#     print("Hello, " + name)
    
    
# greet("fitsum")
    
    
'''Modules and Imports: Modules are Python files containing Python code, and they allow you to organize code logically. You can import modules into your Python scripts using the import statement.
'''
# import math
# import pandas as pd
# import numpy as np



'''
output         we can set the out put by '''


# print (" wlcome to tech tonic tribe ")

# and the second option is 

# name="abebe"

# print (f"welcome {name } how are you today ?")



'''  and the other one is input  we can take the ussesr input
'''

# name = input (" enter your name ")
# print (f"hello {name }")
